title: g8keeper
description: G8Keeper Authentication — documentation
theme: minima
baseurl: "/g8keeper"

url: "https://letuscode.co.uk"

header_pages: []

author: Jason Williams, Software Engineer at LetUsCode

exclude:
  - planning/
  - changelog/

defaults:
  - scope:
      path: ""
    values:
      layout: default
